<a href="https://colab.research.google.com/github/Omarito1980/SIM_YAC_MASAQUIZA_UPSE2023/blob/main/metodo_implicito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math

In [78]:
L= 10000
dx=2500
Tiempo=100000
DT=1000
K=50 #Permeabilidad md
por=0.2 #porosidad
vis=1 #viscocidad cp
Beta = 1 #Factor volumetrico
Comp_Total=1**-6 #psi-1
A= 200000 # area en ft^2


In [79]:
Alpha=K/(vis*por*Comp_Total)

In [80]:
Alpha

250.0

In [81]:
1/Alpha

0.004

In [82]:
Eta=Alpha*DT/(dx**2)
Eta


0.04

In [83]:
# esquema explicito
def Presdt(P0,P1,P2,Eta):
  Pdt=P1+Eta*(P0-2*P1+P2)
  return (Pdt)

In [84]:
Pexplicita=np.zeros((Tiempo//DT,L//dx))

In [85]:
Pexplicita


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [86]:
Pexplicita.shape

(100, 4)

In [75]:
Pyac=1000
Piz=2000
Pder=0
Pin=np.ones(L//dx)
Pres=np.zeros(L//dx)
Pin=Pin*Pyac
Pin[0]=Piz
Pin[len(Pin)-1]=Pder
Pin
Pres


array([0., 0., 0., 0.])

In [87]:
tiempo=DT
Pexplicita[0]=Pin
Pexplicita.shape
while tiempo<Tiempo:
  for i in range(0,len(Pin)-1):
    if i==0:
      Pres[i]=Pin[0]
    elif i==len(Pin)-1:
      Pres[i]=Pin[len(Pin)-1]
    else:
      Pres[i]=Presdt(Pin[i-1],Pin[i],Pin[i+1],Eta)
  Pexplicita[tiempo//DT]=Pres
  tiempo=tiempo+DT
  Pin=Pres    

In [89]:
Pexplicita



array([[2000.        , 1000.        , 1000.        ,    0.        ],
       [2000.        , 1040.        ,  960.        ,    0.        ],
       [2000.        , 1075.2       ,  926.208     ,    0.        ],
       [2000.        , 1106.23232   ,  896.3606528 ,    0.        ],
       [2000.        , 1133.58816051,  869.995327  ,    0.        ],
       [2000.        , 1157.70092075,  846.70373767,    0.        ],
       [2000.        , 1178.9529966 ,  826.12555852,    0.        ],
       [2000.        , 1197.68177921,  807.942785  ,    0.        ],
       [2000.        , 1214.18494827,  791.87476013,    0.        ],
       [2000.        , 1228.72514282,  777.67378504,    0.        ],
       [2000.        , 1241.53408279,  765.12124555,    0.        ],
       [2000.        , 1252.81620599,  754.02419414,    0.        ],
       [2000.        , 1262.75187728,  744.2123337 ,    0.        ],
       [2000.        , 1271.50022044,  735.53535582,    0.        ],
       [2000.        , 1279.201617